name: foram-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cycler=0.10.0
  - expat=2.2.10
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.7
  - glib-tools=2.66.7
  - graphite2=1.3.13
  - gstreamer=1.18.3
  - harfbuzz=2.7.4
  - hdf5=1.10.6
  - icu=68.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.71.1
  - libevent=2.1.10
  - libffi=3.3
  - libglib=2.66.7
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.0.1
  - libopenblas=0.3.12
  - libopencv=4.5.1
  - libpng=1.6.37
  - libpq=12.3
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - numpy=1.20.1
  - olefile=0.46
  - opencv=4.5.1
  - openssl=1.1.1k
  - pcre=8.44
  - pillow=8.1.0
  - pip=21.0.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-opencv=4.5.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyserial=3.5
  - python=3.9.1
  - python-dateutil=2.8.1
  - python_abi=3.9
  - qt=5.12.9
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.34.0
  - tk=8.6.10
  - tornado=6.1
  - tzdata=2021a
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
